# Generated by Django 3.2.25 on 2025-07-03 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='Password',
            new_name='password',
        ),
    ]
